# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='orgname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='presenter',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
