# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171005_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='orgname',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='presenter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('date', 'time', 'title')]),
        ),
    ]
