# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('building_key', models.CharField(max_length=60)),
                ('floor', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('orgname', models.CharField(max_length=60)),
                ('short', models.CharField(max_length=60)),
            ],
        ),
    ]
