# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=60)),
                ('building_key', models.CharField(default='', max_length=60)),
                ('floor', models.CharField(default='', max_length=60)),
                ('name', models.CharField(default='', max_length=60)),
                ('orgname', models.CharField(default='', max_length=60)),
                ('short', models.CharField(max_length=60, unique=True)),
                ('size', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VGN_Coords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('coords', models.CharField(max_length=60, unique=True)),
                ('longitude', models.CharField(max_length=60, unique=True)),
                ('latitude', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
