# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('univis_ref', models.CharField(max_length=60, unique=True)),
                ('univis_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('short', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('lecturer_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.TimeField(default=datetime.datetime(2017, 12, 4, 1, 44, 13, 10710, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=60)),
                ('building_key', models.CharField(default='', max_length=60)),
                ('floor', models.CharField(default='', max_length=60)),
                ('name', models.CharField(default='', max_length=60)),
                ('orgname', models.CharField(default='', max_length=60)),
                ('short', models.CharField(max_length=60, unique=True)),
                ('size', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VGN_Coords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('coords', models.CharField(max_length=60, unique=True)),
                ('longitude', models.CharField(max_length=60, unique=True)),
                ('latitude', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lecture_terms',
            name='room',
            field=models.ManyToManyField(blank=True, to='donar.Room'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='term',
            field=models.ManyToManyField(to='donar.Lecture_Terms'),
        ),
    ]
