# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='short',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
