# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0002_auto_20171028_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_terms',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2017, 10, 28, 17, 59, 39, 456896, tzinfo=utc)),
        ),
    ]
