# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0002_auto_20171030_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_terms',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2017, 10, 29, 23, 30, 14, 805020, tzinfo=utc)),
        ),
    ]
