# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0003_auto_20171004_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGN_Coords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60, unique=True)),
                ('coords', models.CharField(default='', max_length=60, unique=True)),
            ],
        ),
    ]
