# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0003_auto_20180111_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecturer_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='short',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_ref',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='building_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='orgname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='short',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='coords',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='latitude',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='longitude',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
