# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0004_vgn_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgn_coords',
            name='latitude',
            field=models.CharField(default=0, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vgn_coords',
            name='longitude',
            field=models.CharField(default=0, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='coords',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='vgn_coords',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
