# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0003_auto_20171111_1013'),
        ('donar', '0004_auto_20171030_0031'),
    ]

    operations = [
    ]
