# Generated by Django 2.0.1 on 2018-04-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0005_auto_20180401_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecturer_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_id',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_ref',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
