# Generated by Django 2.0.1 on 2018-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0006_auto_20180401_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
