# Generated by Django 2.0.1 on 2018-04-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0007_auto_20180401_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecturer_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_ref',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
