# Generated by Django 2.0.1 on 2018-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0008_auto_20180401_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecturer_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='short',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='univis_ref',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
