# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0010_auto_20171207_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_terms',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2017, 12, 7, 11, 47, 6, 785241, tzinfo=utc)),
        ),
    ]
