# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('starttime', models.DateField(default=django.utils.timezone.now)),
                ('endtime', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SingleFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(to='food.SingleFood'),
        ),
        migrations.AlterUniqueTogether(
            name='happyhour',
            unique_together=set([('date', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('date', 'location')]),
        ),
    ]
