# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlefood',
            old_name='image',
            new_name='food_image',
        ),
    ]
