# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefood',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='food.Allergene'),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='price_employee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='price_guest',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='price_student',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
