# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfoodimage',
            old_name='thumbnail',
            new_name='thumb',
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
