# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
