# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20171008_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happyhour',
            unique_together=set([('date', 'location', 'starttime', 'endtime')]),
        ),
    ]
