# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20171204_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefood',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='food.UserFoodImage'),
        ),
    ]
