# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20171029_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
