# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergene',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('ERBA', 'Erba'), ('MARKUSPLATZ', 'Markusplatz'), ('FEKI', 'Feldkirchenstrasse'), ('AUSTRASSE', 'Austrasse')], max_length=256),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
