# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20171013_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefood',
            name='image',
            field=models.ImageField(blank=True, upload_to='food/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
