# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20171020_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefood',
            name='fifth_star',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='first_star',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='fourth_star',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='second_star',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='third_star',
            field=models.SmallIntegerField(default=0),
        ),
    ]
