# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20171029_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefood',
            name='fifth_star',
        ),
        migrations.RemoveField(
            model_name='singlefood',
            name='first_star',
        ),
        migrations.RemoveField(
            model_name='singlefood',
            name='fourth_star',
        ),
        migrations.RemoveField(
            model_name='singlefood',
            name='second_star',
        ),
        migrations.RemoveField(
            model_name='singlefood',
            name='third_star',
        ),
    ]
