# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20180111_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='food/originals/%Y/%m/%W')),
                ('thumb', models.ImageField(blank=True, upload_to='food/thumbs/%Y/%m/%W')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfoodimage',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='singlefood',
            name='image',
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.FoodImage'),
        ),
        migrations.AddField(
            model_name='singlefood',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.FoodImage'),
        ),
    ]
