# Generated by Django 2.0.1 on 2018-01-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20171204_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(related_name='foods', to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
