# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20171204_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='food/thumbs/%Y/%m/%W'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(related_name='foods', to='food.SingleFood'),
        ),
        migrations.AlterField(
            model_name='userfoodimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='food/originals/%Y/%m/%W'),
        ),
    ]
