# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180113_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/originals/%Y/%m/%W'),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='food/thumbs/%Y/%m/%W'),
        ),
    ]
