# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20180113_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='food.Allergene'),
        ),
    ]
