# Generated by Django 2.0.1 on 2018-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20180117_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefood',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='food.Allergene'),
        ),
    ]
