# Generated by Django 2.0.1 on 2018-03-24 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0008_auto_20180201_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2048)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.SingleFood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AlterUniqueTogether(
            name='userfoodcomment',
            unique_together={('user', 'food')},
        ),
    ]
