# Generated by Django 2.0.1 on 2018-03-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20180324_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHourLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.HappyHourLocation'),
        ),
    ]
