# Generated by Django 2.0.1 on 2018-03-26 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0010_auto_20180325_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happyhour',
            unique_together={('location', 'starttime', 'endtime')},
        ),
        migrations.AlterUniqueTogether(
            name='userfoodrating',
            unique_together={('user', 'food')},
        ),
    ]
