# Generated by Django 2.0.1 on 2018-03-26 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20180326_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodrating',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
