# Generated by Django 2.0.1 on 2018-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20180326_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfoodcomment',
            old_name='comment',
            new_name='description',
        ),
        migrations.AddField(
            model_name='userfoodcomment',
            name='title',
            field=models.CharField(default='Test', max_length=128),
            preserve_default=False,
        ),
    ]
