# Generated by Django 2.0.1 on 2018-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20180330_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefood',
            name='comments',
            field=models.ManyToManyField(blank=True, to='food.UserFoodComment'),
        ),
    ]
