# Generated by Django 2.0.1 on 2018-03-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_singlefood_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(default='NULL', upload_to='food/originals/%Y/%m/%W'),
            preserve_default=False,
        ),
    ]
