# Generated by Django 2.0.1 on 2018-03-31 14:46

import apps.food.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20180331_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(upload_to=apps.food.models.image_path),
        ),
        migrations.AlterField(
            model_name='singlefood',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.FoodImage'),
        ),
    ]
