# Generated by Django 2.0.1 on 2018-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20180331_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='food/thumbs/%Y/%m/%W'),
        ),
    ]
