# Generated by Django 2.0.1 on 2018-03-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_foodimage_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='thumb',
        ),
    ]
