# Generated by Django 2.0.1 on 2018-03-31 16:09

import apps.food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_foodimage_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=apps.food.models.thumb_path),
        ),
    ]
